"""
Simple runner for the valrep

This module loads the config, expands the parameter space,
builds job names, and runs each point through the workflow.
"""

from valrep.workflow_manager import Workflow
from valrep.modifiers import ParameterSpaceModifier, JobNameModifier
from valrep.config_loader import load_config


def run_workflow(config_path, steps_override=None, workdir=None):
    """
    Load the configuration file and run the workflow for each
    parameter point generated by the modifiers.

    Parameters
    ----------
    config_path : str
        Path to the workflow configuration file.
    steps_override : list[str], optional
        If provided, these step names override the ones in the config.
    workdir : str, optional
        Output directory for all generated runs.

    Returns
    -------
    None
        The function prints progress and dispatches each workflow run.
    """
    # Load YAML/JSON config into memory
    config = load_config(config_path)

    # Create workflow instance; default output path is local folder
    workflow = Workflow(config, workdir=workdir or "./all_points_runs")

    # Add workflow steps from CLI override or from the config file
    if steps_override:
        for step_name in steps_override:
            workflow.add_step(step_name)
    else:
        for step_name in config.get("steps", []):
            workflow.add_step(step_name)

    # Set up parameter sweeping + job naming
    param_modifier = ParameterSpaceModifier()
    job_modifier = JobNameModifier()

    # Iterate through all parameter combinations
    for cfg in param_modifier.generate(**config):
        # Attach a unique job name
        cfg = job_modifier.modify(**cfg)
        point_name = cfg["job_name"]

        print(f"\n### POINT: {point_name} ###")

        # Execute the workflow for this parameter point
        result = workflow.run(point_name)

        print(f"Results [{point_name}]: {result}")
