import os
from valrep.step_manager import StepManager

class Workflow:
    """
    Manage and run a sequence of workflow steps for valrep.

    This class handles:
    - Adding steps by name using the StepManager
    - Running steps sequentially for each parameter point
    - Managing output directories for each point
    """

    def __init__(self, config, workdir="./workflow_runs"):
        """
        Initialize the workflow.

        Parameters
        ----------
        config : dict
            Full configuration dictionary containing workflow settings
            and step-specific configurations.
        workdir : str, optional
            Base directory where results of all workflow points will be stored.
            Default is "./workflow_runs".
        """
        self.config = config
        self.workdir = os.path.abspath(workdir)
        os.makedirs(self.workdir, exist_ok=True)

        # List of step instances to run in order
        self.steps = []

        # StepManager handles discovery and instantiation of steps
        self.step_manager = StepManager()

    def add_step(self, step_name: str):
        """
        Add a step instance to the workflow by its name.

        This method looks up the step class from StepManager and
        creates an instance using the step-specific configuration
        if present in the main config.

        Parameters
        ----------
        step_name : str
            Name of the step to add (case-insensitive).

        Example
        -------
        >>> workflow.add_step("madgraph")
        """
        step_config = self.config.get(step_name.lower(), {})
        step = self.step_manager.get_step(step_name, config=step_config)
        self.steps.append(step)

    def run(self, point_name: str):
        """
        Run all workflow steps sequentially for a given parameter point.

        Each step receives the full config, the output directory
        for this point, and the previous step's output.

        Parameters
        ----------
        point_name : str
            Unique name of the parameter point (usually generated by JobNameModifier).

        Returns
        -------
        Any
            The output of the last step in the workflow. This could be
            a filename, data structure, or other object depending on the step.

        Example
        -------
        >>> results = workflow.run("SS_direct.100p0_50p0.13p0")
        """
        point_dir = os.path.join(self.workdir, point_name)
        os.makedirs(point_dir, exist_ok=True)

        prev_output = None
        for step in self.steps:
            print(f"--- Running {step.name} ---")
            prev_output = step.run(self.config, point_dir, prev_output)

        return prev_output
